Traceback (most recent call last):
  File "c:\python39\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "c:\python39\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\matth\AppData\Roaming\Python\Python39\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "c:\python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\python39\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "c:\python39\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "c:\python39\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
Horses = Image.open('horses.jpg')
People = Image.open('people.jpg')
Street = Image.open('street.jpg')
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [1;32mIn[2], line 1[0m
[1;32m----> 1[0m Horses [38;5;241m=[39m [43mImage[49m[38;5;241;43m.[39;49m[43mopen[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mhorses.jpg[39;49m[38;5;124;43m'[39;49m[43m)[49m
[0;32m      2[0m People [38;5;241m=[39m Image[38;5;241m.[39mopen([38;5;124m'[39m[38;5;124mpeople.jpg[39m[38;5;124m'[39m)
[0;32m      3[0m Street [38;5;241m=[39m Image[38;5;241m.[39mopen([38;5;124m'[39m[38;5;124mstreet.jpg[39m[38;5;124m'[39m)

File [1;32mc:\python39\lib\site-packages\PIL\Image.py:3227[0m, in [0;36mopen[1;34m(fp, mode, formats)[0m
[0;32m   3224[0m     filename [38;5;241m=[39m fp
[0;32m   3226[0m [38;5;28;01mif[39;00m filename:
[1;32m-> 3227[0m     fp [38;5;241m=[39m [43mbuiltins[49m[38;5;241;43m.[39;49m[43mopen[49m[43m([49m[43mfilename[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mrb[39;49m[38;5;124;43m"[39;49m[43m)[49m
[0;32m   3228[0m     exclusive_fp [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[0;32m   3230[0m [38;5;28;01mtry[39;00m:

[1;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'horses.jpg'

