Traceback (most recent call last):
  File "c:\python39\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "c:\python39\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\matth\AppData\Roaming\Python\Python39\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "c:\python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\python39\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "c:\python39\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "c:\python39\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Load pretrained Resnet 101 model
model = torchvision.models.segmentation.fcn_resnet101(weights=torchvision.models.segmentation.FCN_ResNet101_Weights.COCO_WITH_VOC_LABELS_V1)

# Set in evaluation mode
model.eval()
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mAttributeError[0m                            Traceback (most recent call last)
Cell [1;32mIn[3], line 2[0m
[0;32m      1[0m [38;5;66;03m# Load pretrained Resnet 101 model[39;00m
[1;32m----> 2[0m model [38;5;241m=[39m torchvision[38;5;241m.[39mmodels[38;5;241m.[39msegmentation[38;5;241m.[39mfcn_resnet101(weights[38;5;241m=[39m[43mtorchvision[49m[38;5;241;43m.[39;49m[43mmodels[49m[38;5;241;43m.[39;49m[43msegmentation[49m[38;5;241;43m.[39;49m[43mFCN_ResNet101_Weights[49m[38;5;241m.[39mCOCO_WITH_VOC_LABELS_V1)
[0;32m      4[0m [38;5;66;03m# Set in evaluation mode[39;00m
[0;32m      5[0m model[38;5;241m.[39meval()

[1;31mAttributeError[0m: module 'torchvision.models.segmentation' has no attribute 'FCN_ResNet101_Weights'

