Traceback (most recent call last):
  File "c:\python39\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "c:\python39\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\matth\AppData\Roaming\Python\Python39\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "c:\python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\python39\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "c:\python39\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "c:\python39\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Get video object
vidcap = cv2.VideoCapture('../../data/motion_detection.mp4')
success,image = vidcap.read()
cv2.imwrite('../../data/motion_detection_1.jpg', image)     # save frame as JPEG file      
success,image = vidcap.read()
cv2.imwrite('../../data/motion_detection_2.jpg', image)     # save frame as JPEG file  
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31merror[0m                                     Traceback (most recent call last)
Cell [1;32mIn[2], line 4[0m
[0;32m      2[0m vidcap [38;5;241m=[39m cv2[38;5;241m.[39mVideoCapture([38;5;124m'[39m[38;5;124m../../data/motion_detection.mp4[39m[38;5;124m'[39m)
[0;32m      3[0m success,image [38;5;241m=[39m vidcap[38;5;241m.[39mread()
[1;32m----> 4[0m [43mcv2[49m[38;5;241;43m.[39;49m[43mimwrite[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43m../../data/motion_detection_1.jpg[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43mimage[49m[43m)[49m     [38;5;66;03m# save frame as JPEG file      [39;00m
[0;32m      5[0m success,image [38;5;241m=[39m vidcap[38;5;241m.[39mread()
[0;32m      6[0m cv2[38;5;241m.[39mimwrite([38;5;124m'[39m[38;5;124m../../data/motion_detection_2.jpg[39m[38;5;124m'[39m, image)     [38;5;66;03m# save frame as JPEG file  [39;00m

[1;31merror[0m: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:787: error: (-215:Assertion failed) !_img.empty() in function 'cv::imwrite'


