Traceback (most recent call last):
  File "c:\python39\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "c:\python39\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\matth\AppData\Roaming\Python\Python39\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "c:\python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\python39\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "c:\python39\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "c:\python39\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Load intrinsic camera matrix
X = np.load('data/intrinsic_camera_properties.npy', allow_pickle=True)
mtx = X.item().get('MTX')
dist = X.item().get('DIST')
rvecs = X.item().get('RVECS')
tvecs = X.item().get('TVECS')

# Termination criteria
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

# Define world coordinates in meters
objp = np.zeros((7 * 7, 3), np.float32)
objp[:, :2] = np.mgrid[0:7, 0:7].T.reshape(-1, 2) * 0.02

# Axis points
origin = [0, 0, 0]
x_point = [0.06, 0, 0]
y_point = [0, 0.06, 0]
z_point = [0, 0, -0.06]
axis = np.float32([x_point, y_point, z_point, origin]).reshape(-1, 3)
box = np.float32([[0.08, 0.06, 0], [0.12, 0.06, 0], [0.12, 0.10, 0], [0.08, 0.10, 0], [0.08, 0.06, -0.04], [0.12, 0.06, -0.04], [0.12, 0.10, -0.04], [0.08, 0.10, -0.04]]).reshape(-1, 3)
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [1;32mIn[3], line 2[0m
[0;32m      1[0m [38;5;66;03m# Load intrinsic camera matrix[39;00m
[1;32m----> 2[0m X [38;5;241m=[39m [43mnp[49m[38;5;241;43m.[39;49m[43mload[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mdata/intrinsic_camera_properties.npy[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43mallow_pickle[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m)[49m
[0;32m      3[0m mtx [38;5;241m=[39m X[38;5;241m.[39mitem()[38;5;241m.[39mget([38;5;124m'[39m[38;5;124mMTX[39m[38;5;124m'[39m)
[0;32m      4[0m dist [38;5;241m=[39m X[38;5;241m.[39mitem()[38;5;241m.[39mget([38;5;124m'[39m[38;5;124mDIST[39m[38;5;124m'[39m)

File [1;32mc:\python39\lib\site-packages\numpy\lib\npyio.py:405[0m, in [0;36mload[1;34m(file, mmap_mode, allow_pickle, fix_imports, encoding, max_header_size)[0m
[0;32m    403[0m     own_fid [38;5;241m=[39m [38;5;28;01mFalse[39;00m
[0;32m    404[0m [38;5;28;01melse[39;00m:
[1;32m--> 405[0m     fid [38;5;241m=[39m stack[38;5;241m.[39menter_context([38;5;28;43mopen[39;49m[43m([49m[43mos_fspath[49m[43m([49m[43mfile[49m[43m)[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mrb[39;49m[38;5;124;43m"[39;49m[43m)[49m)
[0;32m    406[0m     own_fid [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[0;32m    408[0m [38;5;66;03m# Code to distinguish from NumPy binary files and pickles.[39;00m

[1;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'data/intrinsic_camera_properties.npy'

